<?php

/**
 * @file
 * Main file for the Portal Siga module, which is a custom module.
 *
 * @ingroup custom
 */

/**
 * Implements hook_form_alter().
 */
function portal_siga_form_alter(&$form, &$form_state, $form_id) {
  /*
   *if (isset($form['type']) && $form['type']['#value'] . '_node_settings' == $form_id) {
   *  $form['workflow']['upload_' . $form['type']['#value']] = array(
   *    '#type' => 'radios',
   *    '#title' => t('Attachments'),
   *    '#default_value' => variable_get('upload_' . $form['type']['#value'], 1),
   *    '#options' => array(t('Disabled'), t('Enabled')),
   * );
   *}
   */
  if('anuncios_node_form' == $form_id) {
    // $form['#validate'][] = 'portal_siga_endereco_gmaps';
    // $form[''] = array(
    //   '#type' => '',
    //   '#title' => t(''),
    //   '#default_value' => $settings[''],
    //   '#required' => ,
    //   '#element_validate' => array(''),
    //   '#description' => t(''),
    // );

  }

}

function portal_siga_endereco_gmaps(&$form, &$form_state) {
  $endereco = $form_state['values']['field_endereco'][LANGUAGE_NONE][0]['value'];
  $tid = $form_state['values']['field_localizacao'][LANGUAGE_NONE][0]['tid'];

  $bairro = taxonomy_term_load($tid);
  $cidade = taxonomy_get_parents($tid);
  $cidade_tid = array_keys($cidade);
  $estado = taxonomy_get_parents(reset($cidade_tid));

  $bairro = $bairro->name;
  $cidade = reset($cidade)->name;
  $estado = reset($estado)->name;

  $form_state['values']['field_endereco_gmaps'][LANGUAGE_NONE][0]['value'] =
    $endereco . ' ' . $cidade;
}
